version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Running build phase...
      - dotnet publish -c Release
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r build_output.zip ./bin/Release/net6.0/publish/*
artifacts:
  files:
    - build_output.zip
