version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Running build phase...
      - dotnet publish -c Release
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./bin/Release/net6.0/publish/*
  discard-paths: yes
